#!/bin/bash
#############################################################################
# Program : Sync RedMac
# Description : sync files between this folder on Redhat 6 and a folder on rmbp
# Date : May 21st 2014
# Revision : 0.3 
# Updates : Checking the destination folder list 
#############################################################################
# Initialization : 
#############################################################################
usr_mac="cyanjin"
usr_red="cyan"
host_mac="cyanrmbp.wv-wifi.mentorg.com"
host_red="calintern6"
path_mac="/Users/cyanjin/cpd/"
path_red="/home/cyan/Desktop/programs/share/"
#############################################################################
#############################################################################

res_ping=`ping $host_mac -c 1 | grep "ping: unknown host"`
if [[ -z $res_ping ]];then
	rsync -auzv --del $path_red $usr_mac@$host_mac:$path_mac  # reverse timestamp update newer file recursively compressed
fi

